import { StyleSheet } from 'react-native';
import { ThemeManager } from '../../../../ThemeManager';
import { Colors, Fonts } from '../../../theme';

export default StyleSheet.create({
  textStyle5: {
    fontSize: 14,
    fontFamily: Fonts.dmMedium,
    color: '#1A202E',
    alignSelf: 'center',
  },
  textStyle4: {
    fontSize: 36,
    fontFamily: Fonts.dmMedium,
    color: '#1A202E',
    alignSelf: 'center',
  },
  textStyle3: {
    fontSize: 14,
    fontFamily: Fonts.dmMedium,
    color: '#64748B',
    alignSelf: 'center',
  },
  textStyle2: {
    marginTop: 15,
    fontSize: 14,
    fontFamily: Fonts.dmRegular,
    color: '#64748B',
    alignSelf: 'center',
    textAlign: 'center',
  },
  customTxtstyle1: {
    color: '#1A202E',
    fontSize: 16,
    fontFamily: Fonts.dmMedium,
  },
  customTxtstyle: {
    color: '#64748B',
    fontSize: 14,
    fontFamily: Fonts.dmRegular,
  },
  ViewStyle3: {
    alignSelf: 'center',
    height: 250,
    width: 250,
    borderWidth: 5,
    borderColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
  },
  textStyle1: {
    fontSize: 15,
    marginTop: 20,
    fontFamily: Fonts.dmMedium,
    color: '#1A202E',
  },
  textStyle: {
    alignSelf: 'center',
    fontSize: 16,
    fontFamily: Fonts.dmMedium,
    marginTop: 10,
    color: '#64748B',
  },
  ViewStyle: {
    width: 15,
    height: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ViewStyle1: {
    width: 14,
    height: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  wrap: {
    display: 'flex',
    flex: 1,
    backgroundColor: Colors.White,
    paddingHorizontal: 23,
    paddingTop: 71,
  },
  qrBlock: {
    alignItems: 'center',
    marginTop: 25,
    marginBottom: 25,
  },
  qrAddress: {
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 20,
    marginHorizontal: 60,
    fontFamily: Fonts.dmMedium,
    fontSize: 14,
  },
  qrAddressTextStyle: {
    fontFamily: Fonts.dmMedium,
    fontSize: 14,
    color: Colors.textColor,
    paddingHorizontal: 1,
    textAlign: 'center',
  },
  copyShareButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
  },
  copyShareButtonsText: {
    fontFamily: Fonts.dmSemiBold,
    fontSize: 16,
    color: ThemeManager.colors.text_color,
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 12,
  },
  QrText: {
    fontFamily: Fonts.dmSemiBold,
    fontSize: 20,
    color: '#1A202E',
    textAlign: 'center',
  },
  buttonsStyle: {
    borderRadius: 10,
    marginLeft: 5,
    padding: 15,
    borderWidth: 1,
  },

  ViewStyle2: {
    borderRadius: 20,
    marginHorizontal: 20,
  },
  centeredView: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    elevation: 1,
  },
  modalView: {
    backgroundColor: Colors.successColor,
    borderRadius: 12,
    padding: 20,
    width: '90%',
    borderWidth: 1,
  },
  blurView: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    flex: 1,
  },
  errorText: {
    fontFamily: Fonts.dmRegular,
    color: Colors.lossColor,
    fontSize: 14,
    marginTop: 5,
  },
  sendCodeStyle: {
    alignSelf: 'flex-end',
    fontSize: 16,
    fontFamily: Fonts.dmRegular,
    marginTop: 8,
  },
});
