import { StyleSheet } from 'react-native';
import { Colors, Fonts } from '../../../theme';

export default StyleSheet.create({
  ViewStyle3: {
    fontSize: 14,
    fontFamily: Fonts.dmMedium,
    color: '#1A202E',
    alignSelf: 'center',
  },
  ViewStyle1: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 15,
  },
  textStyle7: {
    fontSize: 36,
    fontFamily: Fonts.dmMedium,
    color: '#1A202E',
    alignSelf: 'center',
  },
  textStyle6: {
    fontSize: 14,
    fontFamily: Fonts.dmMedium,
    color: '#64748B',
    alignSelf: 'center',
  },
  textStyle5: {
    marginTop: 15,
    fontSize: 14,
    fontFamily: Fonts.dmRegular,
    color: '#64748B',
    alignSelf: 'center',
    textAlign: 'center',
  },
  textStyle4: {
    color: '#64748B',
    fontSize: 16,
    fontFamily: Fonts.dmMedium,
  },
  textStyle3: {
    color: '#1A202E',
    fontSize: 16,
    fontFamily: Fonts.dmMedium,
  },
  textStyle2: {
    color: '#64748B',
    fontSize: 14,
    fontFamily: Fonts.dmRegular,
  },
  textStyle: {
    fontSize: 15,
    marginTop: 20,
    fontFamily: Fonts.dmMedium,
    color: '#1A202E',
  },
  textStyle1: {
    alignSelf: 'center',
    fontSize: 16,
    fontFamily: Fonts.dmMedium,
    marginTop: 10,
    color: '#64748B',
  },
  ViewStyle: {
    alignSelf: 'center',
    height: 250,
    width: 250,
    borderWidth: 5,
    borderColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    borderRadius: 10,
    backgroundColor: '#F1F5F9',
    marginBottom: 10
  },
  ViewStyle2: {
    marginTop: 0,
    borderRadius: 10,
    marginHorizontal: 20,
    // paddingHorizontal: 20
  },
  ViewStyle2: {
    paddingTop: 0,
    borderRadius: 20,
    marginHorizontal: 20,
  },
  sendCodeStyle: {
    alignSelf: 'flex-end',
    fontSize: 16,
    fontFamily: Fonts.dmRegular,
    marginTop: 8,
  },
  errorText: {
    fontFamily: Fonts.dmRegular,
    color: Colors.lossColor,
    fontSize: 14,
    marginTop: 5,
    textAlign: 'right',
  },
  bottomText: {
    fontFamily: Fonts.dmMedium,
    color: Colors.Black,
    fontSize: 16,
    marginTop: 5,
    textAlign: 'right',
  },
  centeredView: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 1,
  },
  modalView: {
    backgroundColor: Colors.successColor,
    borderRadius: 12,
    padding: 20,
    width: '90%',
    borderWidth: 1,
  },
  blurView: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    flex: 1,
  },
  QrText: {
    fontFamily: Fonts.dmSemiBold,
    fontSize: 20,
    color: '#1A202E',
    textAlign: 'center',
  },
  headingText: {
    paddingHorizontal: 20,
    fontFamily: Fonts.dmSemiBold,
    fontSize: 14,
    marginBottom: 10,
  },
});
