import { Dimensions, StyleSheet } from 'react-native';
import { Colors, Fonts } from '../../../theme';
import {
  bottomNotchWidth,
  getDimensionPercentage as dimen,
  heightDimen,
  widthDimen,
} from '../../../Utils';
export default StyleSheet.create({
  transactionHistoryTitle: {
    fontFamily: Fonts.dmSemiBold,
    fontSize: 16,
    textAlign: 'center',
  },
  txtNew11: {
    fontSize: 14,
    fontFamily: Fonts.dmBold,
    lineHeight: 24,
  },
  txtNew123: {
    fontSize: 16,
    fontFamily: Fonts.dmSemiBold,
    lineHeight: 36,
  },
  ViewNew: {
    flexDirection: 'row',
    marginTop: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  img1: {
    transform: [{ rotate: '270deg' }],
    height: 14,
    width: 19,
  },
  ViewStyle9: {
    borderRadius: 20,
    justifyContent: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    marginTop: 10,
  },
  textstyle6: {
    fontSize: 16,
    fontFamily: Fonts.dmSemiBold,
    lineHeight: 49,
    letterSpacing: 0.11,
  },
  textstyle5: {
    fontSize: 14,
    fontFamily: Fonts.dmRegular,
    lineHeight: 24,
    paddingVertical: 25,
  },
  textstyle_5: {
    fontSize: 14,
    fontFamily: Fonts.dmRegular,
    lineHeight: 24,
    marginTop: 10,
  },
  textstyle_4: {
    fontSize: 15,
    fontFamily: Fonts.dmMedium,
    lineHeight: 24,
    marginTop: 15,
  },
  textstyleNew: {
    fontSize: 40,
    fontFamily: Fonts.dmBold,
    // lineHeight: 89,
    textAlign: 'center',
  },
  touch1: {
    paddingVertical: 15,
    width: '48%',
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: 10,
  },
  touch2: {
    paddingVertical: 15,
    width: '48%',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: 10,
  },
  touch22: {
    paddingVertical: 5,
    width: '48%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 20,
  },
  touchR: {
    // paddingVertical: 5,
    width: '55%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: dimen(20),
  },
  ViewTouch: {
    marginHorizontal: 20,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 24,
  },
  txtNew12: {
    marginLeft: 12,
  },
  imgStyle112: {
    alignSelf: 'center',
    height: 15,
    width: 15,
  },
  buttonstyle: {
    borderWidth: 1,
    borderColor: Colors.Black,
  },
  txtUpgrade1: {
    fontSize: 18,
    fontFamily: Fonts.dmBold,
    lineHeight: 34,
    letterSpacing: 0.13,
    textAlign: 'left',
    marginTop: 15,
  },
  txtUpgrade: {
    fontSize: 14,
    fontFamily: Fonts.dmRegular,
    lineHeight: 24,
    textAlign: 'left',
    width: '45%',
  },
  txtNew: {
    fontSize: 14,
    fontFamily: Fonts.dmRegular,
  },
  txtNew1: {
    fontSize: 16,
    fontFamily: Fonts.dmMedium,
    lineHeight: 36,
  },
  ViewText: {
    // marginHorizontal: 20,
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderRadius: 20,
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  btnStyle: {
    borderWidth: 1,
    alignSelf: 'center',
    width: '92%',
    fontFamily: Fonts.dmBold,
    fontSize: 18,
    color: Colors.txt_new,
    // lineHeight: 39,
    // letterSpacing: 0.13,
    // textAlign: 'center',
    marginBottom: dimen(16),
  },
  ViewStyleNew: {
    // marginTop: 54,
    justifyContent: 'flex-end',
    flex: 1,
    // backgroundColor:'pink'
    // marginBottom: 15,
  },
  imgStyle: {
    alignSelf: 'center',
    height: dimen(202),
    width: dimen(306),
  },
  ViewStyle8: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ViewStyle7: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 0.1,
    top: 28,
  },
  imgView: {
    height: 25,
    width: 25,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: Colors.border,
  },
  textstyle3: {
    fontSize: 16,
    fontFamily: Fonts.dmSemiBold,
    lineHeight: 27,
  },
  textstyle4: {
    fontSize: 14,
    fontFamily: Fonts.dmRegular,
    lineHeight: 24,
    color: 'rgba(0, 0, 0, 0.6)',
  },
  ViewStyle6: {
    padding: 16,
    backgroundColor: Colors.bg1,
    borderRadius: 10,
    shadowColor: '#0000001A',
    width: '100%',
    shadowOpacity: 4,
    elevation: 4,
  },
  textstyle2: {
    // backgroundColor: 'red',
    top: 28,
    flex: 0.2,
    fontSize: 14,
    fontFamily: Fonts.dmRegular,
    lineHeight: 24,
    color: Colors.textColorNew,
    marginLeft: 10,
  },
  ViewStyle5: {
    justifyContent: 'center',
    marginVertical: 10,
    flex: 1,
  },
  ViewStyle4: {
    paddingVertical: 5,
    justifyContent: 'center',
    marginVertical: 5,
    marginHorizontal: 12,
    borderRadius: 10,
  },
  ViewStyle3: {
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  ViewStyle2: {
    marginTop: 225,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  ViewStyle1: {
    minHeight: 95,
    paddingHorizontal: 20,
    width: '100%',
    borderRadius: 10,
    justifyContent: 'center',
  },
  ViewStyle: {
    alignSelf: 'center',
    position: 'absolute',
    zIndex: 16,
  },
  txt: {
    marginLeft: 22,
    marginTop: 110,
    fontFamily: Fonts.dmRegular,
    fontSize: 14,
    lineHeight: 27,
    textAlign: 'left',
  },
  txt1: {
    fontFamily: Fonts.dmRegular,
    fontSize: 16,
    lineHeight: 27,
    textAlign: 'center',
    marginHorizontal: 60,
  },
  textstyle: {
    fontFamily: Fonts.dmRegular,
    fontSize: 16,
    color: Colors.txt_new,
    lineHeight: 27,
  },
  textstyle1: {
    fontFamily: Fonts.dmBold,
    fontSize: 16,
    // letterSpacing: 0.18,
    lineHeight: 49,
    // marginTop: -5,
  },
  textstyle_: {
    fontFamily: Fonts.dmSemiBold,
    fontSize: 16,
    lineHeight: 27,
  },
  myStyle: {
    alignSelf: 'center',
    width: '92%',
    fontFamily: Fonts.dmBold,
    fontSize: 18,
    color: Colors.txt_new,
    lineHeight: 39,
    letterSpacing: 0.13,
    textAlign: 'center',
    marginBottom: dimen(20),
  },
  txt2: {
    fontFamily: Fonts.dmRegular,
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  codeBg: {
    borderRadius: 7,
    paddingVertical: 8,
    paddingHorizontal: 10,
    justifyContent: 'center',
    backgroundColor: Colors.btnBg,
    marginBottom: 5,
  },
  imgStyle1: {
    marginTop: 25,
    resizeMode: 'contain',
    alignSelf: 'center',
    width: Dimensions.get('screen').width + 25,
  },
  imgStyle11: {
    // borderRadius: 15,
    paddingTop: 59,
    marginTop: 25,
    paddingHorizontal: 20,
    width: Dimensions.get('screen').width - 45,
    height: 210,
  },
  rewardTxt: {
    marginTop: 20,
    fontFamily: Fonts.dmSemiBold,
    fontSize: 16,
    lineHeight: 27,
    textAlign: 'left',
  },
  addressWrap: {
    marginTop: 5,
    minHeight: 56,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginHorizontal: 15,
    borderWidth: 1,
  },
  addressItem: {
    paddingLeft: 15,
    flex: 0.95,
    // backgroundColor: 'red',
    height: 56,
    borderRightWidth: 1,
    justifyContent: 'center',
  },
  addressItemText: {
    fontFamily: Fonts.dmRegular,
    fontSize: 16,
  },
  addressButtons: {
    flexDirection: 'row',
    paddingRight: 10,
  },
  addButtons: {
    width: 30,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textstyle_1: {
    fontSize: 15,
    fontFamily: Fonts.dmRegular,
    lineHeight: 24,
    paddingVertical: 25,
    textAlign: 'center',
    marginTop: -35,
    paddingHorizontal: 22,
  },
});
