-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTAiSovht4DRs9k16
WHH0Sp5SAOKWO6EEcAu5o3eULlegCgYIKoZIzj0DAQehRANCAAQMuDyJf2HSxNuy
SlhngBllPMMGVIum0y+OUPf1JsTmmpDSGd1lg6DTsTAYGXXutQaRl7LZxqDIvRRI
3ST/yvnI
-----END PRIVATE KEY-----