import React from 'react';
import { StyleSheet } from 'react-native';
import { Scene, Router, Tabs } from 'react-native-router-flux';
import SendBnbPol from './components/screens/SendBnbPol/SendBnbPol';
import Walkthrough from './components/screens/Walkthrough/Walkthrough';
import { CustomTabBar } from './components/common/CustomTabBar';
import Singleton from './Singleton';
import Manage from './components/screens/Manage/Manage';
import CreatePriceAlert from './components/screens/CreatePriceAlert';
import PriceAlert from './components/screens/PriceAlert/PriceAlert';
import AddressBook from './components/screens/AddressBook/AddressBook';
import AddContact from './components/screens/AddContact/AddContact';
import Notifications from './components/screens/Notifications/Notifications';
import PrivacyPolicy from './components/screens/PrivacyPolicy/PrivacyPolicy';
import PrepaidCard from './components/screens/PrepaidCard/PrepaidCard';
import {
  ApplyFilter,
  Welcome,
  CrossChain,
  Settings,
  DefiAccessMain,
  SelectCoin,
  Send,
  SendBtc,
  WalletMain,
  CreatePin,
  DetailTransaction,
  TransactionHistory,
  Security,
  AddCustomToken,
  CreateNewWallet,
  EnterPin,
  Currency,
  AboutUs,
  EnterPinForTransaction,
  ConfirmPin,
  EnterPinSecurity,
  CreatePinSecurity,
  ConfirmPinSecurity,
  Receive,
  Swap,
  Portfolio,
  WalletStats,
  WatchList,
  UpdateWatchList,
  Buy,
  Sell,
  CheckoutNew,
  SendMatic,
  ManageWallet,
  ToggleWalletNew,
  ContactsBook,
  DetailCrossChain,
  Alchemy,
  SendTrx,
  Announcements,
  NotificationsTab,
  VirtualCard,
  Referral,
  VirtualAndPhysical, DepositCard, DepositCalculate,
  CardTransactionHistory,
  DappBrowserNew,
  BuyNew,
  Transak,
  SellNew,
  ContactUs,
  HelpTab,
  SupportHistory,
  SupportTicket,
  Language,
  ReferralRoadMap,
  ReferralRewards,
  Upgrade,
  PayFee,
  Terms,
  PhysicalCard,
  ThemeChange,
  Onboarding,
  Legal,
  WalletName,
  ImportWallet,
  SecretPhrase,
  VerifySecretPhrase,
  ManageOnboarding,
  ManageImportWallet,
  ManageVerifySecretPhrase,
  WalletManageList,
  UpdateWalletName,
  ExportPrivateKeys,
  ShowRecoveryPhrase,
  PrivateKey,
  OneInchSwap,
  MyWalletList,
  BuySellCoin,
  AlreadyHaveWallet,
  ImportWalletByPrivateKey,
  SendSol,
  WalletConnection
} from './components/screens/index';
import LinkPhysicalCard from './components/screens/LinkPhysicalCard/LinkPhysicalCard';
import ActivePhysicalCard from './components/screens/ActivatePhysicalCard/ActivePhysicalCard';
import USPrefCardKYC from './components/screens/USPrefCardKYC/USPrefCardKYC';
import USPreferdCardScreen from './components/screens/USpreferedCardScreen/USPreferdCardScreen';
import VirtualCardScreen from './components/screens/VirtualCardScreen/VirtualCardScreen';
import SelectChain from './components/screens/SelectChain/SelectChain';
import CreateMakerAccount from './components/screens/CreateMakerAccount/CreateMakerAccount';
import BuySellWebview from './components/screens/BuySellWebview/BuySellWebview';
import TermsandConditions from './components/screens/TermsandConditions/TermsandConditions';

const RouterComponent = ({ onRouteChanged }) => {
  return (
    <Router
      onStateChange={onRouteChanged}
      navigationBarStyle={{
        backgroundColor: "rgba(0,0,0,0)",
        borderBottomWidth: 0,
      }}
      hideNavBar={false}
      titleStyle={{ color: "#000" }}
    >
      <Scene key="root" hideNavBar>
        <Scene
          key="Welcome"
          hideNavBar={true}
          component={Welcome}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Onboarding"
          hideNavBar={true}
          component={Onboarding}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Legal"
          hideNavBar={true}
          component={Legal}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="WalletName"
          hideNavBar={true}
          component={WalletName}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ImportWallet"
          hideNavBar={true}
          component={ImportWallet}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="SecretPhrase"
          hideNavBar={true}
          component={SecretPhrase}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="VerifySecretPhrase"
          hideNavBar={true}
          component={VerifySecretPhrase}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ManageOnboarding"
          hideNavBar={true}
          component={ManageOnboarding}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ManageImportWallet"
          hideNavBar={true}
          component={ManageImportWallet}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ManageVerifySecretPhrase"
          hideNavBar={true}
          component={ManageVerifySecretPhrase}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="WalletManageList"
          hideNavBar={true}
          component={WalletManageList}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="UpdateWalletName"
          hideNavBar={true}
          component={UpdateWalletName}
          gestureEnable={false}
          panHandlers={null}
        />

        <Scene
          key="Walkthrough"
          hideNavBar={true}
          component={Walkthrough}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ConfirmPin"
          hideNavBar={true}
          component={ConfirmPin}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Manage"
          hideNavBar={true}
          component={Manage}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="CreateNewWallet"
          hideNavBar={true}
          component={CreateNewWallet}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          //  initial
          key="PrepaidCard"
          hideNavBar={true}
          component={PrepaidCard}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Currency"
          hideNavBar={true}
          component={Currency}
          gestureEnable={false}
          panHandlers={null}
        />

        <Scene
          key="CrossChain"
          hideNavBar={true}
          component={CrossChain}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="OneInchSwap"
          hideNavBar={true}
          component={OneInchSwap}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="SelectCoin"
          hideNavBar={true}
          component={SelectCoin}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Send"
          hideNavBar={true}
          component={Send}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="SendBtc"
          hideNavBar={true}
          component={SendBtc}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="SendBnbPol"
          hideNavBar={true}
          component={SendBnbPol}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="SendSol"
          hideNavBar={true}
          component={SendSol}
          gestureEnable={false}
          panHandlers={null}
        />

        <Scene
          key="Receive"
          hideNavBar={true}
          component={Receive}
          gestureEnable={false}
          panHandlers={null}
        />

        <Scene
          key="VirtualCard"
          hideNavBar={true}
          component={VirtualCard}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="DepositCard"
          hideNavBar={true}
          component={DepositCard}
          gestureEnable={false}
          panHandlers={null}
        />

        <Scene
          key="DepositCalculate"
          hideNavBar={true}
          component={DepositCalculate}
          gestureEnable={false}
          panHandlers={null}
        />

        <Scene
          key="EnterPin"
          hideNavBar={true}
          component={EnterPin}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="EnterPinForTransaction"
          hideNavBar={true}
          component={EnterPinForTransaction}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="CreatePin"
          hideNavBar={true}
          component={CreatePin}
          gestureEnable={false}
          panHandlers={null}
        />
        <Tabs
          key="Main"
          showLabel={false}
          wrap={false}
          lazy={true}
          tabBarComponent={(props) => {
            return (
              <CustomTabBar
                {...props}
                ref={(ref) => {
                  Singleton.bottomBar = ref;
                }}
              />
            );
          }}
          swipeEnabled={false}
          gestureEnable={false}
          panHandlers={null}
        >
          <Scene
            hideNavBar={true}
            key="WalletMain"
            component={WalletMain}
            gestureEnable={false}
            panHandlers={null}
          />
          <Scene
            hideNavBar={true}
            key="Swap"
            component={Swap}
            gestureEnable={false}
            panHandlers={null}
          />
          <Scene
            hideNavBar={true}
            key="Portfolio"
            component={Portfolio}
            gestureEnable={false}
            panHandlers={null}
          />
          <Scene
            hideNavBar={true}
            key="DefiAccessMain"
            component={DefiAccessMain}
            gestureEnable={false}
            panHandlers={null}
          />
          <Scene
            hideNavBar={true}
            key="Settings"
            component={Settings}
            gestureEnable={false}
            panHandlers={null}
          />
        </Tabs>
        <Scene
          hideNavBar={true}
          key="PrivacyPolicy"
          component={PrivacyPolicy}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          hideNavBar={true}
          key="AddContact"
          component={AddContact}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          hideNavBar={true}
          key="AddressBook"
          component={AddressBook}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          hideNavBar={true}
          key="Notifications"
          component={Notifications}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          hideNavBar={true}
          key="PriceAlert"
          component={PriceAlert}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          hideNavBar={true}
          key="CreatePriceAlert"
          component={CreatePriceAlert}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="TransactionHistory"
          hideNavBar={true}
          component={TransactionHistory}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Security"
          hideNavBar={true}
          component={Security}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="AddCustomToken"
          hideNavBar={true}
          component={AddCustomToken}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="DetailTransaction"
          hideNavBar={true}
          component={DetailTransaction}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="AboutUs"
          hideNavBar={true}
          component={AboutUs}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="EnterPinSecurity"
          hideNavBar={true}
          component={EnterPinSecurity}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="CreatePinSecurity"
          hideNavBar={true}
          component={CreatePinSecurity}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ConfirmPinSecurity"
          hideNavBar={true}
          component={ConfirmPinSecurity}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="WalletStats"
          hideNavBar={true}
          component={WalletStats}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="WatchList"
          hideNavBar={true}
          component={WatchList}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="UpdateWatchList"
          hideNavBar={true}
          component={UpdateWatchList}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="UpdateWatchList"
          hideNavBar={true}
          component={UpdateWatchList}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Buy"
          hideNavBar={true}
          component={Buy}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="CheckoutNew"
          hideNavBar={true}
          component={CheckoutNew}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="SendMatic"
          hideNavBar={true}
          component={SendMatic}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ApplyFilter"
          hideNavBar={true}
          component={ApplyFilter}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ManageWallet"
          hideNavBar={true}
          component={ManageWallet}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ToggleWalletNew"
          hideNavBar={true}
          component={ToggleWalletNew}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ContactsBook"
          hideNavBar={true}
          component={ContactsBook}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="DetailCrossChain"
          hideNavBar={true}
          component={DetailCrossChain}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Alchemy"
          hideNavBar={true}
          component={Alchemy}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Sell"
          hideNavBar={true}
          component={Sell}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="SendTrx"
          hideNavBar={true}
          component={SendTrx}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Announcements"
          hideNavBar={true}
          component={Announcements}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="NotificationsTab"
          hideNavBar={true}
          component={NotificationsTab}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Referral"
          hideNavBar={true}
          component={Referral}
          gestureEnable={false}
          panHandlers={null}
        />

        <Scene
          key="VirtualAndPhysical"
          hideNavBar={true}
          component={VirtualAndPhysical}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="CardTransactionHistory"
          hideNavBar={true}
          component={CardTransactionHistory}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="LinkPhysicalCard"
          hideNavBar={true}
          component={LinkPhysicalCard}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="PhysicalCard"
          hideNavBar={true}
          component={PhysicalCard}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ActivePhysicalCard"
          hideNavBar={true}
          component={ActivePhysicalCard}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="USPrefCardKYC"
          hideNavBar={true}
          component={USPrefCardKYC}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="USPreferdCardScreen"
          hideNavBar={true}
          component={USPreferdCardScreen}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="VirtualCardScreen"
          hideNavBar={true}
          component={VirtualCardScreen}
          gestureEnable={false}
          panHandlers={null}
        />

        <Scene
          key="DappBrowserNew"
          hideNavBar={true}
          component={DappBrowserNew}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="BuyNew"
          hideNavBar={true}
          component={BuyNew}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Transak"
          hideNavBar={true}
          component={Transak}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="SellNew"
          hideNavBar={true}
          component={SellNew}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ContactUs"
          hideNavBar={true}
          component={ContactUs}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="HelpTab"
          hideNavBar={true}
          component={HelpTab}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="SupportTicket"
          hideNavBar={true}
          component={SupportTicket}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="SupportHistory"
          hideNavBar={true}
          component={SupportHistory}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Language"
          hideNavBar={true}
          component={Language}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ReferralRoadMap"
          hideNavBar={true}
          component={ReferralRoadMap}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ReferralRewards"
          hideNavBar={true}
          component={ReferralRewards}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Upgrade"
          hideNavBar={true}
          component={Upgrade}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="PayFee"
          hideNavBar={true}
          component={PayFee}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="Terms"
          hideNavBar={true}
          component={Terms}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ThemeChange"
          hideNavBar={true}
          component={ThemeChange}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ExportPrivateKeys"
          hideNavBar={true}
          component={ExportPrivateKeys}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ShowRecoveryPhrase"
          hideNavBar={true}
          component={ShowRecoveryPhrase}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="PrivateKey"
          hideNavBar={true}
          component={PrivateKey}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="MyWalletList"
          hideNavBar={true}
          component={MyWalletList}
          gestureEnable={false}
          panHandlers={null}
        />

        <Scene
          key="SelectChain"
          hideNavBar={true}
          component={SelectChain}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="CreateMakerAccount"
          hideNavBar={true}
          component={CreateMakerAccount}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="BuySellCoin"
          hideNavBar={true}
          component={BuySellCoin}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="BuySellWebview"
          hideNavBar={true}
          component={BuySellWebview}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="TermsandConditions"
          hideNavBar={true}
          component={TermsandConditions}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="AlreadyHaveWallet"
          hideNavBar={true}
          component={AlreadyHaveWallet}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="ImportWalletByPrivateKey"
          hideNavBar={true}
          component={ImportWalletByPrivateKey}
          gestureEnable={false}
          panHandlers={null}
        />
        <Scene
          key="WalletConnection"
          hideNavBar={true}
          component={WalletConnection}
          gestureEnable={false}
          panHandlers={null}
        />
      </Scene>
    </Router>
  );
};


export default RouterComponent;


